version: '2'
services:
    nginx:
      # используем последний стабильный образ nginx
        image: nginx:latest
        # маршрутизируем порты
        ports:
            - "8101:80"
        environment:
            TZ: Europe/Moscow
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php-fpm
    php-fpm:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        # build: ./images/php-fpm
        image: klek07/php-fpm-oci8:latest
        # этот образ будет общаться с mysql
        links:
            - mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
        environment:
            TZ: Europe/Moscow
    mysql:
        image: mariadb
        ports:
            - "3307:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        # задаем пароль для root пользователя
        environment:
            MYSQL_ROOT_PASSWORD: gren@der_dba
            TZ: Europe/Moscow
#    pma:
#      # используем последний стабильный образ phpmyadmin
#        image: phpmyadmin/phpmyadmin
#        restart: always
#        links:
#            - mysql:mysql
#        ports:
#            - 8183:80
#        environment:
#            # прописываем название нашего MySQL хоста
#            PMA_HOST: mysql
#            MYSQL_USERNAME: root
#            MYSQL_ROOT_PASSWORD: secret
